### ISSUE TITLE
PRACTICA 1 UNIDAD 3 PREPOSICIONES LOGICOS

### ISSUE THREAD

**Issue by LenninGS-0** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-LenninGS-0#1]
[prac1 mate u3.pdf](https://github.com/user-attachments/files/17439517/prac1.mate.u3.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
